services:
  db:
    image: postgres:15-alpine
    container_name: lapisbaja-db
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: lapisbaja_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - lapisbaja-net

  redis:
    image: redis:alpine
    container_name: lapisbaja-redis
    restart: always
    networks:
      - lapisbaja-net

  api:
    build: ./api
    container_name: lapisbaja-api
    restart: always
    depends_on:
      - db
      - redis
    # Menggunakan port agar bisa diakses Nginx VPS
    ports:
      - "8080:8080"
    env_file: ./api/.env
    networks:
      - lapisbaja-net

  web:
    build: ./web
    container_name: lapisbaja-web
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
    env_file: ./web/.env
    networks:
      - lapisbaja-net

networks:
  lapisbaja-net:
    driver: bridge
